CREATE TABLE athletes (
    athlete_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    sex ENUM('M', 'F', 'O')
);
CREATE TABLE `countries` (
    NOC CHAR(3) NOT NULl PRIMARY KEY,
    name CHAR(50)
);

CREATE TABLE `teams` (
    team_id INT PRIMARY KEY AUTO_INCREMENT,
    NOC CHAR(3) NOT NULL,
    team_name VARCHAR(255) NOT NULL
);

CREATE TABLE `olympics` (
    olympics_id INT PRIMARY KEY AUTO_INCREMENT,
    games VARCHAR(255) NOT NULL,
    year SMALLINT,
    season ENUM('Summer', 'Winter'),
    city VARCHAR(255) NOT NULL
);

CREATE TABLE `sports` (
    sport_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE `events` (
    event_id INT PRIMARY KEY AUTO_INCREMENT,
    olympics_id INT,
    sport_id INT,
    event_name VARCHAR(255) NOT NULL,
    FOREIGN KEY (olympics_id) REFERENCES olympics(olympics_id),
    FOREIGN KEY (sport_id) REFERENCES sports(sport_id)
);

CREATE TABLE `athlete_events` (
    athlete_id INT,
    team_id INT,
    event_id INT,
    medal ENUM('Gold', 'Silver', 'Bronze', 'NA'),
    weight INT,
    height INT,
    age INT,
    PRIMARY KEY (athlete_id, event_id, team_id, medal),
    FOREIGN KEY (athlete_id) REFERENCES athletes(athlete_id),
    FOREIGN KEY (team_id) REFERENCES teams(team_id),
    FOREIGN KEY (event_id) REFERENCES events(event_id)
);

CREATE TABLE `users` (
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(50) NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    points INT DEFAULT 0,
    UNIQUE(user_name)
);

CREATE TABLE `country_preferences` (
    preference_id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    preference_value CHAR(3),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (preference_value) REFERENCES countries(NOC)
);

CREATE TABLE `year_preferences` (
    preference_id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    preference_param VARCHAR(10),
    preference_value SMALLINT,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE `sports_preferences` (
    preference_id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    preference_value INT,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (preference_value) REFERENCES sports(sport_id)
);

CREATE TABLE `question_templates` (
    template_id INT PRIMARY KEY,
    template_query VARCHAR(255) NOT NULL,
    template_text VARCHAR(255) NOT NULL
);

CREATE TABLE `question_template_params` (
    param_id INT PRIMARY KEY,
    template_id INT,
    param_value VARCHAR(255),
    FOREIGN KEY (template_id) REFERENCES question_templates(template_id)
);

CREATE TABLE `questions` (
    question_id INT PRIMARY KEY,
    question_template_id INT,
    user_id INT,
    generated_question_text VARCHAR(255) NOT NULL
);

CREATE TABLE `user_progress` (
    user_id INT,
    question_id INT,
    answer_id INT,
    is_correct BOOLEAN,
    points_earned INT,
    bonus_points_earned INT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, question_id, timestamp)
);

CREATE TABLE `answers` (
    answer_id INT PRIMARY KEY AUTO_INCREMENT,
    question_id INT,
    answer_text VARCHAR(255),
    is_correct BOOLEAN NOT NULL,
    points INT NOT NULL DEFAULT 0
);

INSERT INTO countries (NOC, name) VALUES
('AFG', 'Afghanistan'),
('AHO', 'Curacao'),
('ALB', 'Albania'),
('ALG', 'Algeria'),
('AND', 'Andorra'),
('ANG', 'Angola'),
('ANT', 'Antigua and Barbuda'),
('ANZ', 'Australasia'),
('ARG', 'Argentina'),
('ARM', 'Armenia'),
('ARU', 'Aruba'),
('ASA', 'American Samoa'),
('AUS', 'Australia'),
('AUT', 'Austria'),
('AZE', 'Azerbaijan'),
('BAH', 'Bahamas'),
('BAN', 'Bangladesh'),
('BAR', 'Barbados'),
('BDI', 'Burundi'),
('BEL', 'Belgium'),
('BEN', 'Benin'),
('BER', 'Bermuda'),
('BHU', 'Bhutan'),
('BIH', 'Bosnia and Herzegovina'),
('BIZ', 'Belize'),
('BLR', 'Belarus'),
('BOH', 'Bohemia'),
('BOL', 'Boliva'),
('BOT', 'Botswana'),
('BRA', 'Brazil'),
('BRN', 'Bahrain'),
('BRU', 'Brunei'),
('BUL', 'Bulgaria'),
('BUR', 'Burkina Faso'),
('CAF', 'Central African Republic'),
('CAM', 'Cambodia'),
('CAN', 'Canada'),
('CAY', 'Cayman Islands'),
('CGO', 'Republic of Congo'),
('CHA', 'Chad'),
('CHI', 'Chile'),
('CHN', 'China'),
('CIV', 'Ivory Coast'),
('CMR', 'Cameroon'),
('COD', 'Democratic Republic of the Congo'),
('COK', 'Cook Islands'),
('COL', 'Colombia'),
('COM', 'Comoros'),
('CPV', 'Cape Verde'),
('CRC', 'Costa Rica'),
('CRO', 'Croatia'),
('CRT', 'Crete'),
('CUB', 'Cuba'),
('CYP', 'Cyprus'),
('CZE', 'Czech Republic'),
('DEN', 'Denmark'),
('DJI', 'Djibouti'),
('DMA', 'Dominica'),
('DOM', 'Dominican Republic'),
('ECU', 'Ecuador'),
('EGY', 'Egypt'),
('ERI', 'Eritrea'),
('ESA', 'El Salvador'),
('ESP', 'Spain'),
('EST', 'Estonia'),
('ETH', 'Ethiopia'),
('EUN', 'Russia'),
('FIJ', 'Fiji'),
('FIN', 'Finland'),
('FRA', 'France'),
('FRG', 'Germany'),
('FSM', 'Micronesia'),
('GAB', 'Gabon'),
('GAM', 'Gambia'),
('GBR', 'UK'),
('GBS', 'Guinea-Bissau'),
('GDR', 'Germany'),
('GEO', 'Georgia'),
('GEQ', 'Equatorial Guinea'),
('GER', 'Germany'),
('GHA', 'Ghana'),
('GRE', 'Greece'),
('GRN', 'Grenada'),
('GUA', 'Guatemala'),
('GUI', 'Guinea'),
('GUM', 'Guam'),
('GUY', 'Guyana'),
('HAI', 'Haiti'),
('HKG', 'Hong Kong'),
('HON', 'Honduras'),
('HUN', 'Hungary'),
('INA', 'Indonesia'),
('IND', 'India'),
('IOA', 'Individual Olympic Athletes'),
('IRI', 'Iran'),
('IRL', 'Ireland'),
('IRQ', 'Iraq'),
('ISL', 'Iceland'),
('ISR', 'Israel'),
('ISV', 'Virgin Islands'),
('ITA', 'Italy'),
('IVB', 'Virgin Islands, British'),
('JAM', 'Jamaica'),
('JOR', 'Jordan'),
('JPN', 'Japan'),
('KAZ', 'Kazakhstan'),
('KEN', 'Kenya'),
('KGZ', 'Kyrgyzstan'),
('KIR', 'Kiribati'),
('KOR', 'South Korea'),
('KOS', 'Kosovo'),
('KSA', 'Saudi Arabia'),
('KUW', 'Kuwait'),
('LAO', 'Laos'),
('LAT', 'Latvia'),
('LBA', 'Libya'),
('LBR', 'Liberia'),
('LCA', 'Saint Lucia'),
('LES', 'Lesotho'),
('LIB', 'Lebanon'),
('LIE', 'Liechtenstein'),
('LTU', 'Lithuania'),
('LUX', 'Luxembourg'),
('MAD', 'Madagascar'),
('MAL', 'Malaysia'),
('MAR', 'Morocco'),
('MAS', 'Malaysia'),
('MAW', 'Malawi'),
('MDA', 'Moldova'),
('MDV', 'Maldives'),
('MEX', 'Mexico'),
('MGL', 'Mongolia'),
('MHL', 'Marshall Islands'),
('MKD', 'Macedonia'),
('MLI', 'Mali'),
('MLT', 'Malta'),
('MNE', 'Montenegro'),
('MON', 'Monaco'),
('MOZ', 'Mozambique'),
('MRI', 'Mauritius'),
('MTN', 'Mauritania'),
('MYA', 'Myanmar'),
('NAM', 'Namibia'),
('NBO', 'North Borneo'),
('NCA', 'Nicaragua'),
('NED', 'Netherlands'),
('NEP', 'Nepal'),
('NFL', 'Newfoundland'),
('NGR', 'Nigeria'),
('NIG', 'Niger'),
('NOR', 'Norway'),
('NRU', 'Nauru'),
('NZL', 'New Zealand'),
('OMA', 'Oman'),
('PAK', 'Pakistan'),
('PAN', 'Panama'),
('PAR', 'Paraguay'),
('PER', 'Peru'),
('PHI', 'Philippines'),
('PLE', 'Palestine'),
('PLW', 'Palau'),
('PNG', 'Papua New Guinea'),
('POL', 'Poland'),
('POR', 'Portugal'),
('PRK', 'North Korea'),
('PUR', 'Puerto Rico'),
('QAT', 'Qatar'),
('RHO', 'Zimbabwe'),
('ROT', 'Refugee Olympic Team'),
('ROU', 'Romania'),
('RSA', 'South Africa'),
('RUS', 'Russia'),
('RWA', 'Rwanda'),
('SAA', 'Germany'),
('SAM', 'Samoa'),
('SCG', 'Serbia and Montenegro'),
('SEN', 'Senegal'),
('SEY', 'Seychelles'),
('SIN', 'Singapore'),
('SKN', 'Turks and Caicos Islands'),
('SLE', 'Sierra Leone'),
('SLO', 'Slovenia'),
('SMR', 'San Marino'),
('SOL', 'Solomon Islands'),
('SOM', 'Somalia'),
('SRB', 'Serbia'),
('SRI', 'Sri Lanka'),
('SSD', 'South Sudan'),
('STP', 'Sao Tome and Principe'),
('SUD', 'Sudan'),
('SUI', 'Switzerland'),
('SUR', 'Suriname'),
('SVK', 'Slovakia'),
('SWE', 'Sweden'),
('SWZ', 'Swaziland'),
('SYR', 'Syria'),
('TAN', 'Tanzania'),
('TCH', 'Czech Republic'),
('TGA', 'Tonga'),
('THA', 'Thailand'),
('TJK', 'Tajikistan'),
('TKM', 'Turkmenistan'),
('TLS', 'Timor-Leste'),
('TOG', 'Togo'),
('TPE', 'Taiwan'),
('TTO', 'Trinidad and Tobago'),
('TUN', 'Tunisia'),
('TUR', 'Turkey'),
('TUV', 'Tuvalu'),
('UAE', 'United Arab Emirates'),
('UAR', 'United Arab Republic'),
('UGA', 'Uganda'),
('UKR', 'Ukraine'),
('UNK', 'Unknown'),
('URS', 'Russia'),
('URU', 'Uruguay'),
('USA', 'USA'),
('UZB', 'Uzbekistan'),
('VAN', 'Vanuatu'),
('VEN', 'Venezuela'),
('VIE', 'Vietnam'),
('VIN', 'Saint Vincent'),
('VNM', 'Vietnam'),
('WIF', 'West Indies Federation'),
('YAR', 'North Yemen'),
('YEM', 'Yemen'),
('YMD', 'South Yemen'),
('YUG', 'Yugoslavia'),
('ZAM', 'Zambia'),
('ZIM', 'Zimbabwe');